- name: testplaybook
  hosts: testclients
  become: true

  tasks:
    - name: Set Timezone
      command: timedatectl set-timezone Europe/Berlin

    - name: Update and Upgrade Packages
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Install QEMU Guest Agent
      apt:
        name: qemu-guest-agent
        state: present
      notify:
        - Enable and Start QEMU Guest Agent

    - name: Disable Cloud-Init
      shell: |
        touch /etc/cloud/cloud-init.disabled
        dpkg-reconfigure cloud-init
        apt-get purge -y cloud-init
        rm -rf /etc/cloud/
        rm -rf /var/lib/cloud/
      args:
        warn: false

  handlers:
    - name: Enable and Start QEMU Guest Agent
      service:
        name: qemu-guest-agent
        state: started
        enabled: true
